name: Kingdoms-2
main: com.imdeity.kingdoms.main.KingdomsMain
version: 12.07.30
author: vanZeben
website: http://dev.bukkit.org/server-mods/kingdoms-2/
depend: [DeityAPI, DeityProtect]
commands:
    Kingdoms:
        aliases: []
    Kingdom:
        aliases: []
    Plot:
        aliases: []
    Resident:
        aliases: [res]
    Town:
        aliases: []
    KingdomsAdmin:
        aliases: [ka]