name: Kingdoms-2
main: com.imdeity.kingdoms.main.KingdomsMain
version: 12.08.07.02
author: vanZeben
website: http://dev.bukkit.org/server-mods/kingdoms-2/
depend: [DeityAPI, DeityProtect]
commands:
    Kingdoms:
        aliases: []
    Kingdom:
        aliases: [k]
    Plot:
        aliases: [p]
    Resident:
        aliases: [res]
    Town:
        aliases: [t]
    KingdomsAdmin:
        aliases: [ka]
    TownChat:
        aliases: [tc]
    KingdomChat:
        aliases: [kc]